### ISSUE TITLE
problem with module

### ISSUE THREAD

**Issue by aeespinosao** [ssuperczynski/ngx-easy-table#145]
Hi, 
I am trying to work with ngx-easy-table but i have an error and i dont know how to solve it, can you say me how to solve it?

```
ERROR in Error: Metadata version mismatch for module C:/Users/andre/Documents/METIS/microSegurosFront/node_modules/ngx-easy-table/ngx-easy-table.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/Users/andre/Documents/METIS/microSegurosFront/src/app/app.module.ts, resolving symbol AppModule in C:/Users/andre/Documents/METIS/microSegurosFront/src/app/app.module.ts
    at syntaxError (C:\Users\andre\Documents\METIS\microSegurosFront\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (C:\Users\andre\Documents\METIS\microSegurosFront\node_modules\@angular\compiler\bundles\compiler.umd.js:25118:23)
    at StaticReflector.simplify (C:\Users\andre\Documents\METIS\microSegurosFront\node_modules\@angular\compiler\bundles\compiler.umd.js:25130:13)
    at StaticReflector.annotations (C:\Users\andre\Documents\METIS\microSegurosFront\node_modules\@angular\compiler\bundles\compiler.umd.js:24558:41)
    at _getNgModuleMetadata (C:\Users\andre\Documents\METIS\microSegurosFront\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (C:\Users\andre\Documents\METIS\microSegurosFront\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (C:\Users\andre\Documents\METIS\microSegurosFront\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Users\andre\Documents\METIS\microSegurosFront\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (C:\Users\andre\Documents\METIS\microSegurosFront\node_modules\@ngtools\webpack\src\plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\Users\andre\Documents\METIS\microSegurosFront\node_modules\@ngtools\webpack\src\plugin.js:443:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ssuperczynski** [comment]
Hey, 
probably old package in the node_modules. Could you `rm -rf node_modules` and `npm install`.
Could if it doesn't work, could you provide your angular version, and ngx-easy-table version.

**Comment by ssuperczynski** [comment]
Closing, no response, hope it helped :)
