### ISSUE TITLE
Error in ./AppComponent class AppComponent: value.slice is not a function

### ISSUE THREAD

**Issue by robertellis100** [ssuperczynski/ngx-easy-table#30]
Error including ng2-easy-table with Angular2 QuickStart.
**Error:**

```
EXCEPTION: Error in ./AppComponent class AppComponent - inline template:31:8
ORIGINAL EXCEPTION: TypeError: value.slice is not a function
ORIGINAL STACKTRACE:
TypeError: value.slice is not a function
at SearchPipe.transform (http://localhost:3000/node_modules/ng2-easy-table/dist/app/pipes/header-pipe.js:37:48)
at eval (http://localhost:3000/node_modules/@angular/core/src/linker/view_utils.js:188:22)
at DebugAppView._View_AppComponent0.detectChangesInternal (AppComponent.template.js:258:299)
at DebugAppView.AppView.detectChanges (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:200:14)
at DebugAppView.detectChanges (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:289:44)
at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:220:34)
at DebugAppView._View_MyApp0.detectChangesInternal (MyApp.template.js:92:8)
at DebugAppView.AppView.detectChanges (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:200:14)
at DebugAppView.detectChanges (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:289:44)
at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:220:34)
ERROR CONTEXT:
[object Object]
```

**Error may be caused by ng2-easy-table not able to correctly use configuration. Not sure where to go from here.**

![error1tb2](https://cloud.githubusercontent.com/assets/13954708/15253825/2b26ad78-18f1-11e6-8eba-76f5e33a2179.png)

As suggested on the ng2-easy-table readMe, there are needs for changes to files to include ng2-easy-table. My changes and additions to incoporate ng2-easy-table with Angular2 QuickStart files can be found at my repo [myang2tableproj2](https://github.com/robertellis100/myang2tableproj2).

**Comment by robertellis100** [comment]
Should the app/data.json file be shaped a certain way? What type of object is ng2-easy-table expecting to receive?

**Comment by ssuperczynski** [comment]
App has been upgraded to new Angular 4.4 with tons of new features.
Please check https://github.com/ssuperczynski/ngx-easy-table/wiki or https://stackblitz.com/edit/angular-2xhnud?embed=1&file=app/app.component.ts for config or JSON examples. 🍻
